# Setup
title:        Minh Triet Tran's Home
tagline:      Linux  - Devops - Networking
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Triet Tran Minh
  url:        https://www.linkedin.com/in/trietminhtran/

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown